"""empty message

Revision ID: 9a7334adf0f9
Revises: 
Create Date: 2022-09-11 15:57:00.174980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a7334adf0f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('price_min', sa.Numeric(), nullable=True),
    sa.Column('price_max', sa.Numeric(), nullable=True),
    sa.Column('price_tick', sa.Numeric(), nullable=True),
    sa.Column('amount_min', sa.Numeric(), nullable=True),
    sa.Column('amount_max', sa.Numeric(), nullable=True),
    sa.Column('amount_tick', sa.Numeric(), nullable=True),
    sa.Column('total_min', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_markets_id'), 'markets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_markets_id'), table_name='markets')
    op.drop_table('markets')
    # ### end Alembic commands ###
